### PR TITLE
use new ledgerjs library

### PR DESCRIPTION
**Pull request by lenondupe**

### CODE REVIEW

**Comment by lenondupe** [comment]
The new ledgerjs library is hosted here: https://github.com/LedgerHQ/ledgerjs
The browserified file included in index.html was generated from here: https://github.com/lenondupe/ledgerjs-stellar

**Comment by lenondupe** [comment]
This PR needs to be updated with a new version of the browserified ledgerjs library file to add compatibility with upcoming Ledger Stellar app version 3. You can create it with [this project here](https://github.com/lenondupe/ledgerjs-stellar).

**Comment by lenondupe** [comment]
New Ledger Stellar app v3 was released today.

**Comment by little-wave** [comment]
Already done. I'll close this.

**Pull request closed without merging**
